spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
  h2:
    console:
      enabled: true
      path : /h2-console
  datasource :
    url : jdbc:h2:~/local;MODE=MariaDB
    driverClassName : org.h2.Driver
    username : sa
    password :
  mail:
    host: smtp.gmail.com
    port: 587
    username: zzandi.dev@gmail.com
    password: mzsbxaueqvjjrpoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true